apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zlworw3g5-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a7bbf23e9b.tmzl.p3.openshiftapps.com/rhtap/rhtap-qe:a0983d54cc17fc685628c9682ab78a5310bec537@sha256:2a6ceb5c9f11343be9b0ec304521170518f8de0b8478ab3c690193715bf21740
          name: container-image
